apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: "blablablalbla"
  namespace: "blablablalbla"-config
spec:
  exportTo:
  - workspaces:
    - name: ops-team
  importFrom:
  - workspaces:
    - name: ops-team
  options:
    serviceIsolation:               # enable service isolation and Istio Sidecar resource
      enabled: false
      trimProxyConfig: false